// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function JenkinsLogs() {
  return window['go']['main']['App']['JenkinsLogs']();
}

export function JenkinsState() {
  return window['go']['main']['App']['JenkinsState']();
}

export function JenkinsURL() {
  return window['go']['main']['App']['JenkinsURL']();
}
