// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function JenkinsLogs():Promise<string>;

export function JenkinsState():Promise<Record<string, any>>;

export function JenkinsURL():Promise<string>;
